packages:
  ########
  bqt: ##
  ######
    # NOTE: trees is to be set in distribution
    name: BeCute
    description: |
      A simple qt abstraction layer, and repository for generalized widgets
    url: https://github.com/Byron/bqt
    requires:
      # these requirements are to be defined in the distribution
      - pyside
      - bcore
    environment:
      variables:
        PYTHONPATH: src/python
  beg-qt:
    requires: bqt
  bcmdg-qt:
    requires: bqt
  bprocessg-qt:
    requires: bqt
  beg-qt-exec:
    # client must define a package called e.g 'beg', which requires this package and defines an alias
    # for starting it. We just define the startup code
    arguments:
      prepend:
        - -m
        - beg.qt
  
